### ISSUE TITLE
Dark variant doesn't work with @apply directive

### ISSUE THREAD

**Issue by mquandalle** [windicss/svelte-windicss-preprocess#672] opened 2022-09-24 08:45 UTC
### Describe the bug

See reproduction https://stackblitz.com/edit/sveltejs-kit-template-default-p8gsnc?file=src/routes/+page.svelte

The `dark:` modifier doesn't work in a component with the apply directive:

```svelte
<p>This text should be red</p>

<style>
	p {
		@apply dark:text-red-600;
	}
</style>
```

However it works if I explicitly add a wrapper with `dark` class inside the component:

```svelte
<div class="dark">
  <!-- we souldn't need this class because 
  it's already set at the root of the DOM -->
  <p>This text is red as expected</p>
</div>

<style>
	p {
		@apply dark:text-red-600;
	}
</style>
```

But unless I miss something the `dark` modifier shouldn't be scoped to components, otherwise I have to add an extra wrapper in all components to handle dark mode.

### System Info

```shell
System:
    OS: Linux 5.19 Pop!_OS 22.04 LTS
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 1.90 GB / 15.39 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.16.0/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
  IDEs:
    Nano: 6.2 - /usr/bin/nano
    Sublime Text: 4107 - /usr/bin/subl
    VSCode: 1.70.2 - /usr/bin/code
  Browsers:
    Brave Browser: 101.1.38.111
    Chrome: 105.0.5195.102
    Chromium: 105.0.5195.125
    Firefox: 104.0.1
  npmPackages:
    svelte: ^3.50.1 => 3.50.1 
    windicss: ^3.5.6 => 3.5.6
```

### Used Package Manager

npm

**Comment by alexanderniebuhr** [comment] 2022-09-24 14:45
Yeah, that is a scoping issue, as well as an issue that svelte removes unused classes in files. contributions welcome.

**Comment by mquandalle** [comment] 2022-09-25 14:35
I think it should generate `:global(.dark) rest-of-selector` to fix the issue?

**Comment by alexanderniebuhr** [comment] 2022-10-01 08:16
I think using the global attribute fixes that right?

```css
<style global>
</style>
```

**Comment by alexanderniebuhr** [comment] 2022-10-01 08:18
otherwise it is an duplicate of https://github.com/windicss/svelte-windicss-preprocess/issues/507

**Closed by alexanderniebuhr** 2022-10-01 08:18 UTC
Labels: enhancement, good first issue, flavor/sveltekit

**Comment by mquandalle** [comment] 2022-10-01 15:55
Hum `<style global>` or `<style windi:global>` doesn't seem to fix the issue (cf. reproduction in OP)
