### ISSUE TITLE
ParseError: Identifier `deep` is expected

### ISSUE THREAD

**Issue by OysterD3** [windicss/svelte-windicss-preprocess#63] opened 2021-03-10 23:54 UTC
```bash
[!] (plugin svelte) ParseError: Identifier `deep` is expected
node_modules/@responsive-ui/loader/src/Loader.svelte
34:   border-width: 2px;
35: }
36: // .responsive-ui-loader__spinner:after {
     ^
37:   //   content: "";
38:   //   width: 5px;
```

The comment in `<style>` is identified as deep selector.

**Comment by alexanderniebuhr** [comment] 2021-03-11 06:40
can you explain the bug a bit more? What does it mean? Never saw this. Could you provide source and converted output somehow?

**Comment by OysterD3** [comment] 2021-03-11 07:04
Here is my `preprocess` config:
```js
// ...
preprocess = [
  sveltePreprocess.typescript(),
  sveltePreprocess.scss(),
  windicssPreprocess.preprocess({
    config: tailwindConfig,
    compile: true,
    prefix: "windi-", // set compilation mode style prefix
    globalPreflight: true, // set preflight style is global or scoped
    globalUtility: true, // set utility style is global or scoped
  }),
];
```

The error I mentioned, it was thrown from [csstree](https://github.com/csstree/csstree), which svelte is depending on it.
If I remove windicssPreprocess from the array, it works fine.

```js
// ...
// working example
preprocess = [
  sveltePreprocess.typescript(),
  sveltePreprocess.scss(),
];
```
___
Now I am having another error.
We have packaged our [components](https://github.com/wetix/responsive-ui) as open-source
```bash
[!] (plugin svelte) ParseError: Unterminated string constant
node_modules/@responsive-ui/label/src/Label.svelte
 8: </script>
 9: 
10: <label class="responsive-ui-label {className" for={forName} {form} {style}>
                                                ^
11:   {label}
12: </label>
ParseError: Unterminated string constant
```

Not sure whether this is related to #35

**Comment by alexanderniebuhr** [comment] 2021-03-11 07:20
yes, i might know the issue here. not sure if beta.9 (ETA later today) will fix it.
Please post any new info and issues here as well

**Comment by alexanderniebuhr** [comment] 2021-03-11 19:13
https://github.com/windicss/svelte-windicss-preprocess/releases/tag/v3.0.0-beta.9

**Comment by OysterD3** [comment] 2021-03-11 22:12
The issue for `ParseError: Identifier `deep` is expected` exists, beta.9 doesn't fix.

**Comment by alexanderniebuhr** [comment] 2021-03-12 06:29
@OysterD3 which component do you have it in?

**Comment by OysterD3** [comment] 2021-03-12 06:46
> @OysterD3 which component do you have it in?

### Issue 1

[@responsive-ui/loader](https://github.com/wetix/responsive-ui/tree/master/components/loader)
```bash
# 1.1
[!] (plugin svelte) ParseError: Unterminated string constant
node_modules/@responsive-ui/loader/src/Loader.svelte
 7:   <div class="responsive-ui-loader" in:fade out:fade>
 8:     <div
 9:       class="responsive-ui-loader__spinner responsive-ui-loader__spinner--{size"
                                                                                   ^
10:     />
11:   </div>
```

[@responsive-ui/input](https://github.com/wetix/responsive-ui/tree/master/components/input)
```bash
# 1.2
[!] (plugin svelte) ParseError: Unterminated string constant
node_modules/@responsive-ui/input/src/Input.svelte
20: <input
21:   {...$$restProps}
22:   class="responsive-ui-input {className"
                                           ^
23:   class:responsive-ui-input--bordered={bordered}
24:   bind:this={ref}
```

Not sure whether because of this [6b7fdad](https://github.com/windicss/svelte-windicss-preprocess/commit/6b7fdad) doesn't accept other variables name

___

### Issue 2

```bash
[!] (plugin svelte) ParseError: Identifier `deep` is expected
apps/web/src/pages/movie/cinemas/index.svelte
342:   align-items: center;
343: }
344: .cinema-helper .filter // p {
                             ^
345:   //   color: var(--color-light-grey, #b9b9b9);
346:   //   padding-right: 10px;
```

This is how I wrote my `style (lang=scss)`
```scss
.cinema-helper {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 5px 15px;
    // ...

    .filter {
      display: flex;
      justify-content: center;
      align-items: center;
      // p {
      //   color: var(--color-light-grey, #b9b9b9);
      //   padding-right: 10px;
      // }
      
      // ...
    }
  }
```

___

### Issue 3 (Similar to Issue 2)
```bash
[!] (plugin svelte) ParseError: Identifier is expected
apps/web/src/pages/movie/cinemas/index.svelte
305: }
306: .empty-state {
307:   // position: absolute;
         ^
308:   top: 0;
309:   left: 0;
```
```scss
// style.scss
.empty-state {
    // position: absolute;
    top: 0;
    left: 0;
    bottom: 0;
    right: 0;
  }
```

**Comment by alexanderniebuhr** [comment] 2021-03-12 07:00
@OysterD3 i cannot reproduce issue 1. My Output on your component looks like following -> in your log, you are missing the last `}` after size
``` svelte
<div class="responsive-ui-loader" in:fade out:fade>
  <div class="responsive-ui-loader__spinner responsive-ui-loader__spinner--{size}" />
</div>
```

**Comment by OysterD3** [comment] 2021-03-12 07:03
> ahh i think it might be an issue with comments in css (I must fix it). is your CSS in different file or in `<style></style>` tags?

In `<style></style>` tags, thanks!

**Comment by alexanderniebuhr** [comment] 2021-03-12 08:20
@OysterD3 issue 2 & 3 are caused by single line comments in your style. 
currently only `/* */` are supported by windicss.. upstream windicss will support `//` in the future..

**Comment by alexanderniebuhr** [comment] 2021-03-12 12:10
you might also be able to get some help on the discord. Link somewhere on default windicss repo discussion

**Comment by OysterD3** [comment] 2021-03-16 14:37
New issue found

```svelte
{#if hasPoster}
  <div class="thumbnail" class:small={posterSize === "extra-small"}>
    <Poster
      hasBorderRadius={!cardView}
      hasBoxShadow={!cardView}
      imageUrl={movie.thumbnailUrl}
      movieTag={movie.tag}
      size={posterSize}
    />
  </div>
{/if}
```

will get this error

```bash
[!] (plugin svelte) ParseError: Expected }
apps/web/src/components/movie/Detail.svelte
24: <div class="movie" class:showtime data-key="{movie.key}">
25:   {#if hasPoster}
26:     <div class="thumbnail all:{posterSize all:=== all:'extra-small'}" class:sm>
                                              ^
27:       <Poster hasBorderRadius="{!cardView}" hasBoxShadow="{!cardView}" imageUrl="{movie.thumbnailUrl}" movieTag="{movie.tag}" size="{posterSize}" />
28:     </div>
```

**Comment by alexanderniebuhr** [comment] 2021-03-16 15:58
working on it

**Comment by alexanderniebuhr** [comment] 2021-03-16 16:15
@OysterD3 actually which version do you use?

**Comment by alexanderniebuhr** [comment] 2021-03-16 16:28
@OysterD3 https://github.com/windicss/svelte-windicss-preprocess/releases/tag/v3.0.0-beta.15

**Comment by OysterD3** [comment] 2021-03-16 21:41
Single line comment in `<script></script>` will comment the rest of the code 
![image](https://user-images.githubusercontent.com/7383278/111383614-6c716100-86e3-11eb-9cda-15ff568c0b83.png)

**Comment by alexanderniebuhr** [comment] 2021-03-16 22:17
I will check that. I am afraid that single line comment are not supported yet. Just block comments.

**Comment by alexanderniebuhr** [comment] 2021-03-17 08:21
@OysterD3 you know for now.. beta.17 please

**Comment by OysterD3** [comment] 2021-03-17 08:39
@alexanderniebuhr I am having this now.
![image](https://user-images.githubusercontent.com/7383278/111438464-3b267e80-873f-11eb-9965-9251134c6d70.png)

Not sure what is the cause. Might related to [this](https://github.com/prettier/prettier/issues/2276)

**Comment by alexanderniebuhr** [comment] 2021-03-17 08:44
i have reverted the feature with [beta.18](https://github.com/windicss/svelte-windicss-preprocess/releases/tag/v3.0.0-beta.18) 
it has to much bugs right now.. so now it should work like before.. not throwing to many bugs.. please keep up your help with posting bugs

however multile line class attributes are now a known bug, like

```svelte
<div class="style-1
   style-1" />
```

**Comment by OysterD3** [comment] 2021-03-18 08:49
![image](https://user-images.githubusercontent.com/7383278/111598111-d1bf7200-8809-11eb-9b2f-cb89a3f7692d.png)
Having this error now. Thanks for your effort!

**Comment by alexanderniebuhr** [comment] 2021-03-18 10:20
@OysterD3 can you show me the source of that function?

**Comment by alexanderniebuhr** [comment] 2021-03-18 10:24
it still seems like the single line comment does break it, but this bug was fixed.. so i wonder why it is still not working for you

**Comment by OysterD3** [comment] 2021-03-18 10:51
> @OysterD3 can you show me the source of that function?

Here you go
```js
// sort by distance
if (coordinate) {
  const [longitude, latitude] = coordinate || [];
  result = result.map((f) => ({
    ...f,
    distance: Number(
      distance(latitude, longitude, f.point[0], f.point[1])
    ),
  }));

  return result
    .filter((v) => searchRes.some((j) => j === v.name))
    .sort((a, b) => {
      if (
        a.key in favCinemas &&
        b.key in favCinemas &&
        a.distance < b.distance
      )
        return -1;
      if (
        a.key in favCinemas &&
        b.key in favCinemas &&
        a.distance > b.distance
      )
        return 1;
      if (a.key in favCinemas && !(b.key in favCinemas)) return -1;
      if (!(a.key in favCinemas) && b.key in favCinemas) return 1;
      if (a.distance < b.distance) return -1;
      if (a.distance > b.distance) return 1;
      return 0;
    });
}
```

**Comment by alexanderniebuhr** [comment] 2021-03-18 10:53
@OysterD3 what version are you on?
it should be fixed already

**Comment by OysterD3** [comment] 2021-03-18 10:54
I am working with `"svelte-windicss-preprocess": "^3.0.0-beta.18"`

**Comment by alexanderniebuhr** [comment] 2021-03-18 10:57
ok that is too old.. try [beta.20](https://github.com/windicss/svelte-windicss-preprocess/releases/tag/v3.0.0-beta.20)

**Comment by alexanderniebuhr** [comment] 2021-03-18 10:59
ok that is too old.. try [beta.21](https://github.com/windicss/svelte-windicss-preprocess/releases/tag/v3.0.0-beta.21)

**Comment by alexanderniebuhr** [comment] 2021-03-18 11:00
ok that is too old.. try [beta.22](https://github.com/windicss/svelte-windicss-preprocess/releases/tag/v3.0.0-beta.22)

**Comment by alexanderniebuhr** [comment] 2021-03-18 11:02
ok that is too old.. try [beta.23](https://github.com/windicss/svelte-windicss-preprocess/releases/tag/v3.0.0-beta.23)

**Comment by alexanderniebuhr** [comment] 2021-03-18 11:05
if that is not working please provide output of following config

```js
module.exports = {
  preprocess: require('svelte-windicss-preprocess').preprocess({
    silent: false,
    debug: true,
    verbosity: 5
  })
}

```

**Comment by OysterD3** [comment] 2021-03-18 11:07
That works, another new issue. SCSS selector
```bash
[!] (plugin svelte) ParseError: Selector is expected
apps/web/src/components/seat/layout.svelte
113: }
114: .seat.tw,
115:     &.bn,
         ^
116:     &.pp .cushion {
117:   background: rgba(210, 42, 248, 0.8);
```

**Comment by OysterD3** [comment] 2021-03-18 11:07
It looks like because of comma, those without comma is fine

**Comment by OysterD3** [comment] 2021-03-18 11:14
Same goes for scss variables

```bash
[!] (plugin svelte) ParseError: Unexpected input
packages/components/src/app-bar/index.svelte
46: }
47: .app-bar.bg {
48:   background: $theme-color;
                  ^
49:   color: #fff;
50: }
```

**Comment by OysterD3** [comment] 2021-03-18 11:29
![image](https://user-images.githubusercontent.com/7383278/111619192-3a194e00-8820-11eb-84e9-f1692c82b845.png)
After removing the issue mentioned above, single-line comment in css. It works!

**Comment by alexanderniebuhr** [comment] 2021-03-18 11:56
@OysterD3 for parsing of css in style tag you might need to open issue in windicss core repo, we are using their css parser

**Comment by alexanderniebuhr** [comment] 2021-03-18 12:33
if you have new bugs please open new issue either in windicss core for style tags or here for other

**Closed by alexanderniebuhr** 2021-03-18 12:33 UTC
Labels: bug
