### ISSUE TITLE
global reset styles disappear in dev mode

### ISSUE THREAD

**Issue by munxar** [windicss/svelte-windicss-preprocess#28] opened 2021-02-23 21:38 UTC
# how to reproduce
- check out this repo
- npm i
- npm run build
- cd example/svelte
- npm i
- npm run dev

Add this markup to the src/App.svelte file:
```html
<script>
  import Feature from './components/Feature.svelte'
</script>
<h1 class="bg-gray-100">a</h1>
<main>
...
```
and hit save. It renders correctly.
Now add one character and hit save:
```html
<script>
  import Feature from './components/Feature.svelte'
</script>
<h1 class="bg-gray-100">ab</h1>
<main>
...
```
Again it renders correctly.
Now remove the last character and hit save:
```html
<script>
  import Feature from './components/Feature.svelte'
</script>
<h1 class="bg-gray-100">a</h1>
<main>
...
```
Now the global reset styles are gone (not added to bundle.css).
This happens to all markup that I already entered. As soon as I enter markup the first time, the global styles are added again. The second time with the same markup -> styles are gone.

Hope it's detailed enough to reproduce.

**Comment by alexanderniebuhr** [comment] 2021-02-24 05:44
Thanks. Had this issue too.. will have a look soon

**Comment by alexanderniebuhr** [comment] 2021-02-24 06:29
@munxar can you please checkout branch `patches/#13-examples` (https://github.com/windicss/svelte-windicss-preprocess/tree/patches/%2313-examples) and test it for me, does it work?
I cannot see the Example breaking with this branch. Can you show screenshot of breaking site?

**Comment by munxar** [comment] 2021-02-24 07:21
@alexanderniebuhr here is a short clip that demonstrates the issue: https://youtu.be/XJesYePjgyA
I found out that there must be at least one tailwind class present in the markup to trigger this bug.
with your patch branch this issue is gone, however plugins like typography are not working (styles are missing).

**Comment by alexanderniebuhr** [comment] 2021-02-24 07:29
Ok can reproduce. Will be fixed, do you have this problem with any other project except the example?

**Comment by munxar** [comment] 2021-02-24 07:41
yes, when I use the svelte-windcss-preprocess in rollup the problem occurs in every project.
with snowpack based projects the problem does not occur.

**Comment by alexanderniebuhr** [comment] 2021-02-24 07:43
I thought that. Rollup is making some weird stuff for us. I have a look into it. Production builds shouldn't be a problem though. Might need some time for this. soz

**Comment by alexanderniebuhr** [comment] 2021-02-24 20:12
closing this in favor of https://github.com/windicss/svelte-windicss-preprocess/issues/32 as this is not special to this case, but seems to be generic

**Closed by alexanderniebuhr** 2021-02-24 20:12 UTC
Labels: bug

**Comment by munxar** [comment] 2021-03-02 22:13
@alexanderniebuhr sorry, but this issue still exists.
I added a unit test that demonstrates this issue in this PR:
https://github.com/windicss/svelte-windicss-preprocess/pull/39

**Comment by alexanderniebuhr** [comment] 2021-03-02 22:25
@munxar i will check tomorrow. I still thing it might be an setup issue..
