### ISSUE TITLE
no global styles in layout in svelte-kit

### ISSUE THREAD

**Issue by mekeor** [windicss/svelte-windicss-preprocess#105] opened 2021-04-08 02:09 UTC
# situation

set up a svelte-kit project and run `npx svelte-add windicss` (which adds `svelte-windicss-preprocess` as dev-dependency, so that's why i'm here). create a `$layout.svelte` with this content:

```html
<style>
  .my-own-class-name { @apply text-indigo-700; }
  a { @apply text-indigo-700; }
</style>
```

and create a page-component with this content:

```html
<ul>
  <li>
    <a class="text-indigo-700" href="/">
      &lt;a class="text-indigo-700" href="/"&gt;
    </a>
  </li>
  <li>
    <a class="my-own-class-name" href="/">
      &lt;a class="my-own-class-name" href="/"&gt;
    </a>
  </li>
  <li>
    <a href="/">
      &lt;a href="/"&gt;
    </a>
  </li>
</ul>
```

# expected behaviour

expect all lines to be colored indigo.

# resulting behaviour

only the first line is colored indigo.

# minimal reproducing example

you can find the whole example here: https://github.com/mekeor/svelte-kit-mwe-bug-css-layout/tree/main/src/routes

**Comment by alexanderniebuhr** [comment] 2021-04-08 04:53
not very familiar with svelte-kit and it's $layout files.. but you can try 

```svelte
<style global>
  .my-own-class-name { @apply text-indigo-700; }
  a { @apply text-indigo-700; }
</style>
```

**Comment by mekeor** [comment] 2021-04-08 16:19
oh, i had thought that i already tested using `global` – but seems like i didn't. thank you for pointing that out. it works!

**Comment by mekeor** [comment] 2021-04-08 18:21
actually, with the `global` attribute, only the two first lines are colored indigo. somehow the third line stays black because of some `a { color: inherit; }` rule which i found within the developer tools.

**Comment by mekeor** [comment] 2021-04-08 18:53
in fact, it works when i use `body a` as a css-selector (in order to style the third line) instead of just `a`.

**Comment by alexanderniebuhr** [comment] 2021-04-08 21:24
i will check this tomorrow.. if you want try our vite plugin.  It is our best supported svelte-kit integration.

**Comment by alexanderniebuhr** [comment] 2021-04-11 07:01
not sure what is wrong with your repo.. never seen this before. i suggest using our [vite plugin ](https://github.com/windicss/vite-plugin-windicss)

**Comment by mekeor** [comment] 2021-04-13 14:08
why do you tag my issue as "invalid", @alexanderniebuhr? and why did you decide that you "won't fix" the issue? why not just let the issue open until someone comes up with an idea?

**Comment by alexanderniebuhr** [comment] 2021-04-13 14:23
because your repo is broken, not the preprocessor..
I took the time and made you a repo which shows it working .. I'll reopen this but won't not remove the labels.
You can compare the two repos and see where the difference is. If you can find a way to reproduce it in my repo, we can handle the bug. but for now it is not reproducible for me

https://github.com/alexanderniebuhr/kit-windicss-debug

**Comment by alexanderniebuhr** [comment] 2021-05-13 08:59
might be fixed with new breaking syntax of v4... docs later today

**Closed by alexanderniebuhr** 2021-05-13 08:59 UTC
Labels: invalid
