### ISSUE TITLE
Preflight CSS in production for Sapper Rollup

### ISSUE THREAD

**Issue by tomasherout** [windicss/svelte-windicss-preprocess#76] opened 2021-03-23 10:04 UTC
Hello,

in my projects preflight CSS is missing when `NODE_ENV` is **not** set to _development_. In other cases (not defined, prod, production and so on) there is no preflight CSS in final page (underline blue hyperlinks, gray buttons etc.).

I have v3.1.1 of svelte-windicss-preprocess and issue is same for Svelte (after hot reload) and for Sapper (in build phase, dev is OK).

Otherwise, your project is cool 👍

**Comment by alexanderniebuhr** [comment] 2021-03-23 10:17
which bundler do you use?

**Comment by tomasherout** [comment] 2021-03-23 10:19
Rollup (in both cases).

**Comment by alexanderniebuhr** [comment] 2021-03-23 10:21
for rollup in Svelte native try:

```js
...
    preprocess: require('svelte-windicss-preprocess').preprocess({
        mode: !production ? "dev": "prod",
        ...
      }),
...
```

the preprocessor has to know if on DEV, so it can generate preflights for HMR

**Comment by tomasherout** [comment] 2021-03-23 11:33
It works for _dev_ npm script (`rollup -c -w`) but _build_ npm script (result in build directory after `rollup -c`) is without preflight.

**Comment by alexanderniebuhr** [comment] 2021-03-23 11:49
I wonder if you have a different setup. I cannot reproduce it currently

**Comment by tomasherout** [comment] 2021-03-23 15:41
Try to clone https://github.com/tomasherout/windicss-no-preflight and then

`yarn install` (or `npm install`)
`npm run build`
`npm run start`

There is:

```svelte
<h1>Caption</h1>

<a href="https://google.com">google.com</a>
```

It should look like this:

<img width="160" alt="image" src="https://user-images.githubusercontent.com/43199492/112174078-69500680-8bf6-11eb-9618-8ab9ab7cb6ff.png">

but looks:

<img width="213" alt="image" src="https://user-images.githubusercontent.com/43199492/112174204-8389e480-8bf6-11eb-8187-27e204cce9aa.png">

**Comment by alexanderniebuhr** [comment] 2021-03-23 17:50
yeah got the bug. will be fixed in next release. might just use `mode: "dev"` hardcoded for now.. it should not have any major drawbacks

**Comment by tomasherout** [comment] 2021-03-24 06:52
Workaround works, many thanks.

**Comment by alexanderniebuhr** [comment] 2021-03-24 07:01
@tomasherout actually for now i ask you to just set `mode: "dev"` staticly as a workaround.
the bug is caused by sapper + rollup which to genereate the preflights without problems but somehow not at the right place for SSR+SPA mode.
Currently I do not see any possibility to change the logic, which will break non sapper projects.. but I can offer you to take a look at the new rollup plugin, might work better for your use case. https://github.com/windicss/vite-plugin-windicss/tree/main/packages/rollup-plugin-windicss

**Comment by kavaro** [comment] 2021-03-26 11:20
I am working on a sapper project and I think I am having the same issue even when using mode: "dev".

Example svelte component
```html
<a href="/">Hello world</a>
```

In development mode, everything works fine.
However, NODE_ENV=production sapper export --legacy results in a link without preflight applied.

My setup is the identical to the one in issue: https://github.com/windicss/svelte-windicss-preprocess/issues/82

**Comment by alexanderniebuhr** [comment] 2021-03-26 12:14
NODE_ENV overrides mode.. so yeah. Also I inform you that we will drop support for sapper since it gets replaced by svelte-kit

**Comment by kavaro** [comment] 2021-03-26 12:27
Ok, will make the switch to svelte-kit, was waiting for it to reach beta, and move from there.


On 26 Mar 2021, at 12:15, Alexander Niebuhr ***@***.******@***.***>> wrote:



NODE_ENV overrides mode.. so yeah. Also I inform you that we will drop support for sapper since it gets replaced by svelte-kit

**Comment by alexanderniebuhr** [comment] 2021-03-26 13:56
> https://github.com/windicss/vite-plugin-windicss/tree/main/packages/rollup-plugin-windicss

you  could always try this with sapper!

**Comment by alexanderniebuhr** [comment] 2021-03-31 14:07
we will sapper support, since svelteKit is close to be released.. for svelteKit Support track readme or #65

**Closed by alexanderniebuhr** 2021-03-31 14:07 UTC
Labels: wontfix
