### ISSUE TITLE
form input styles doesn't work properly

### ISSUE THREAD

**Issue by prab-it** [windicss/svelte-windicss-preprocess#29] opened 2021-02-24 17:47 UTC
Form input styles doesn't work properly, sometimes it works, sometimes it doesn't and sometimes it works partially.
Tested with the latest version of `windicss` + `svelte-windicss-preprocess` on the latest version of `SvelteKit` and `Sapper`.

How to reproduce the issue:
1 - set all the files listed below
2 - `$ npm run dev`
3 - manually refresh the page
4 - `$ npm run build && npm run start`
5 - manually refresh the page

`svelte.config.cjs:`
```js
const sveltePreprocess = require('svelte-preprocess');
module.exports = {
  preprocess: [
    sveltePreprocess.typescript(),
    require('svelte-windicss-preprocess').preprocess({
      config: 'tailwind.config.cjs',
      compile: true,
      prefix: 'css-',
      globalPreflight: true,
      globalUtility: true,
    }),
  ],
  kit: {
    adapter: '@sveltejs/adapter-node',
    target: '#svelte'
  }
};

```
`tailwind.config.cjs:`
```js
module.exports = {
  purge: [],
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {},
  },
  variants: {
    extend: {},
  },
  plugins: [
    require('windicss/plugin/forms')
  ],
}
```
`src/components/Input.svelte:`
```svelte
<script>
  let css;
  export { css as class };
  export let placeholder;
</script>

<input type="text" {placeholder} class="{css} border-gray-300 focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50 rounded-md shadow-sm" />
```
`src/routes/index.svelte:`
```svelte
<script>
  import Input from '$components/Input.svelte';
</script>

<form action="">
  <Input placeholder="component-input" class="block mt-1 ml-1 w-56" />
  <input type="text" placeholder="normal-input" class="block mt-1 ml-1 w-56 border-gray-300 focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50 rounded-md shadow-sm" />
</form>
```

`screenshots:`

![svelte-windicss-issue-1](https://user-images.githubusercontent.com/68732594/109041887-d3e15580-76cf-11eb-84bc-aceec68a8602.png)
![svelte-windicss-issue-2](https://user-images.githubusercontent.com/68732594/109041894-d5ab1900-76cf-11eb-9d6a-a160e55e634a.png)

**Comment by alexanderniebuhr** [comment] 2021-02-24 18:30
Can adapt  your `svelte.config.cjs` to the following and post the logging of svelte-windicss-preprocess please (both `dev` and `build`)

```javscript
const sveltePreprocess = require('svelte-preprocess');
module.exports = {
  preprocess: [
    sveltePreprocess.typescript(),
    require('svelte-windicss-preprocess').preprocess({
      silent: false, // add this
      debug: true,
      config: 'tailwind.config.cjs',
      compile: true,
      prefix: 'css-',
      globalPreflight: true,
      globalUtility: true,
    }),
  ],
  kit: {
    adapter: '@sveltejs/adapter-node',
    target: '#svelte'
  }
};
```

**Comment by prab-it** [comment] 2021-02-24 18:52
`$ npm run dev`
```console
> svelte-kit dev

│
│ svelte-windicss-preprocess - v2.2.1
│ 
│ - windicss running mode: dev
│ - advanced debug logs: on
│    • compilation mode: enabled
│    • class prefix: css-
│    • global preflights: enabled
│    • global utilities: enabled
│
└──────────
```

`$ npm run build`
```console
> svelte-kit build

│
│ svelte-windicss-preprocess - v2.2.1
│ 
│ - windicss running mode: prod
│ - advanced debug logs: on
│    • compilation mode: enabled
│    • class prefix: css-
│    • global preflights: enabled
│    • global utilities: enabled
│
└──────────
```

**Comment by alexanderniebuhr** [comment] 2021-02-24 19:20
@prab-it the problem is caused by the classes you are giving to the component as props. I think there are two workarounds here:

a) If you put them directly in the component it works as expected I would say.
b) Do not use compile mode, then classes will be global.
Would this work as a workaround for you?

I am going to work on a fix for this problem of props (just might take a moment), however as windicss is handling css generation differently we might need to implement it with a class safelist.

**Comment by prab-it** [comment] 2021-02-24 19:40
@alexanderniebuhr I already know these solutions and they works, but I prefer compile mode and pass class as prop to my components.
Is it a big deal, fix this issue?

**Comment by alexanderniebuhr** [comment] 2021-02-24 19:46
the main issue is, that the props are not parsed in svelte-preprocessor. Only at svelte compile. So this plugin cannot know what your variable css means. We have to decide how to handle this, since we want to keep this project at the preprocess lifecycle step.

We will have an solution for this, currently I am thinking one of the following (in my preferred order):

a) safelist in config, define classes which you definitely need, but are just set in variables and props (same as Vite plugin does)
b) use custom class in style tag with @apply (this lets you keep one classname, but the processor can know which styles to apply)
c) if expression (how curly brackets are handled) compile code temporarily to get classes, then apply them

**Comment by prab-it** [comment] 2021-02-24 19:55
@alexanderniebuhr ok, let's see if we can come up with a better solution.
Thanks for your support! :)

**Comment by alexanderniebuhr** [comment] 2021-02-24 19:57
@prab-it turn set `globalUtility: false`  in your config. You are using, svelte kit, for svelte kit you do not need it, I guess. As it adds links to all stylesheets in the head automatically. You can keep compile and props I think. Let me know if that is an option for you?

**Comment by prab-it** [comment] 2021-02-24 20:06
@alexanderniebuhr nothing, if I set `globalUtility: false` also the class prop stop working...

**Comment by alexanderniebuhr** [comment] 2021-02-24 20:10
closing this in favor of https://github.com/windicss/svelte-windicss-preprocess/issues/32 as this is not special to this case, but seems to be generic to plugins

**Closed by alexanderniebuhr** 2021-02-24 20:10 UTC
Labels: bug
